service: diagnostic-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8

functions:
  api:
    handler: wsgi_handler.handler
    layers:
    - arn:aws:lambda:us-east-1:898466741470:layer:psycopg2-py38:2
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
